//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flight_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddFlight
    {
        public long FlightId { get; set; }
        public string FlightName { get; set; }
        public string FlightModel { get; set; }
        public string FlightCarrier { get; set; }
    }
}
