//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flight_project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlightEntities5 : DbContext
    {
        public FlightEntities5()
            : base("name=FlightEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddFlight> AddFlights { get; set; }
        public virtual DbSet<airport1> airport1 { get; set; }
        public virtual DbSet<Booking2> Booking2 { get; set; }
        public virtual DbSet<Passenger1> Passenger1 { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<scheduleflight2> scheduleflight2 { get; set; }
    }
}
