//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flight_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking2
    {
        public int BookingId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<long> FlightId { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public Nullable<int> ConfirmId { get; set; }
    
        public virtual airport1 airport1 { get; set; }
        public virtual airport1 airport11 { get; set; }
        public virtual Registration Registration { get; set; }
        public virtual scheduleflight2 scheduleflight2 { get; set; }
        public virtual Passenger1 Passenger1 { get; set; }
    }
}
