//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flight_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scheduleflight2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public scheduleflight2()
        {
            this.Booking2 = new HashSet<Booking2>();
        }
    
        public long ScduleId { get; set; }
        public string SourceAirport { get; set; }
        public string DestinationAirport { get; set; }
        public string DepartureTime { get; set; }
        public string ArrivalTime { get; set; }
        public Nullable<long> TotalCost { get; set; }
    
        public virtual airport1 airport1 { get; set; }
        public virtual airport1 airport11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking2> Booking2 { get; set; }
    }
}
