//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flight_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class upi1
    {
        public string Name { get; set; }
        public int UPI_Id { get; set; }
        [DataType(DataType.Password)]
        public Nullable<int> UPI_PIN { get; set; }
    }
}
